### ISSUE TITLE
Link to mycitadel wallet in Readme does not work

### ISSUE THREAD

**Issue by Goosie** [rgb-org/rgb-node#103]
In the Readme is an url mentioned to the mycitael-node wallet, which end in a 404 page.
Could not find on github where this should go to.

**Comment by Goosie** [comment]
Seems it must go to https://github.com/mycitadel

**Comment by dr-orlovsky** [comment]
Not yet released, will fix once it will be out. Thanks!

**Comment by dr-orlovsky** [comment]
Fixed with first beta releases:

https://github.com/mycitadel/mycitadel-node
https://github.com/mycitadel/mycitadel-node
