### ISSUE TITLE
Question about fungible asset known allocations semantics

### ISSUE THREAD

**Issue by claudiosdc** [rgb-org/rgb-node#134]
I am confused about the semantics of the `known_allocations` field of the asset data structure maintained in the RGB node's cache.

At first, I thought that it would include only asset allocations currently in effect. In other words, it would not include asset allocations that were already "spent".

However, looking at the results produced by the latest version of the RGB node program, we notice that allocations previously added to the `known_allocations` field are never removed, suggesting that instead it would include a history of all known allocations to date.

I would appreciate if the intended semantics of the `known_allocations` field could be confirmed.

**Comment by dr-orlovsky** [comment]
Known allocations keep track of everything from the stash which was accepted as a consignment endpoint before - even if these amounts are spent OR not owned by the user. The reason for that is to allow wallets to display the history of the operations and additional details (for instance for the spending party to see whom the funds were sent). It is up to the wallet to detect which of the outputs from the `known_allocations` field are UTXOs and which of them are owned by the user – and display only them as a part of the current balance. That is why the field is named `known_allocations` and not `unspent_acclocations` or `owned_allocations`.

**Comment by dr-orlovsky** [comment]
Action point from the call: to work on the acceptance of the own transfer consignment

**Comment by claudiosdc** [comment]
> Action point from the call: to work on the acceptance of the own transfer consignment

@dr-orlovsky and/or @rajarshimaitra, is anyone working on it yet?

I have done some research on it, and came up with the following conclusions:

1.  The `fungible accept` command, as it is, is not suitable to be used by the sending party to record asset change allocations. The reason for that is two fold: a) while the assignment for the transferred assets has a concealed seal and a revealed amount, the assignment for the asset change is the reverse, having a revealed seal and a concealed amount; and b) while there is a single transferred assets endpoint/assignment, there can be multiple asset change endpoints/assignments.
2. The `fungible transfer` command would need to be changed to output the blinding factor for each of the asset change allocations passed to it (via the -a option).
3. Then the `fungible accept` command would need to be changed to take the list of asset change allocations and their respective blinding factors. However, it seems to me that it might be better to create a separate command to specifically record the asset change allocations that could be called `fungible confirm` (in a reference that the transfer would be confirmed by the sending party). Under the hood, the `fungible confirm` command would still call the `merge` command of the stash daemon, which would need to be adapted to take the list of asset change allocations and their respective blinding factors as an additional optional parameter.

I would appreciate your feedback, and would be willing to work on this implementation myself if you need it.

**Comment by dr-orlovsky** [comment]
After the latest updates to the code (I have already tested them with a full cycle of transfers, including multiple participants, change etc) the system works in the following manner:

1. During transfer operation two consignments are created. The first one keeps all data revealed, it must be kept for the sender. The second one has all data concealed (with the new consignment `finalize` procedure): this is for the sender.
2. RGB cache (known allocations) keeps track of all historical allocations. So the sender may accept local consignment right after sending tx to the network, even before it is mined. Cache will have both previous and new allocation, and the correct one can be selected with Electrum server reporting the mining status for txids linked to that allocations

**Comment by dr-orlovsky** [comment]
Are we done with this question after https://github.com/rgb-org/rgb-node/pull/138?

**Comment by claudiosdc** [comment]
> Are we done with this question after #138?

Yes, the question objective of this issue has been answered a while ago.
